# Homework

### Problem 1
- Write a function `dot_product` to calculate the dot product of two 1 by n arrays. For example:
```
a = array([1, 2, 3, 4])
b = array([2, 3, 4, 5])
dot_product(a,b) = 40
```

In [8]:
#### Your code here
def dot_product(a,b):
    a = np.matrix(a)
    b = np.matrix(b).T
    return a*b

In [9]:
#### Test
import numpy as np
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])
dot_product(a, b)

matrix([[40]])

- Given a 1 by n array `a`, write a function `odd(a)` to return a new array containing elements whose index is an odd number.
```
a = np.array([1, 3, 4, 2, 5, 3, 8, 1])
odd(a) = array([3, 2, 3, 1])
```

In [38]:
#### Your code here
def odd(a):
    index = np.arange(len(a))
    index = index[index%2!=0]
    return a[index]

In [39]:
#### Test

a = np.array([1, 3, 4, 2, 5, 3, 8, 1])
odd(a)

array([3, 2, 3, 1])

### Problem 2
Construct the following arrays without listing all the elements. For example, you should use **np.ones(3)** to generate a array *array([1, 1, 1])* instead of **np.array([1, 1, 1])**.

(1) Construct an array of **float** ranging from 0-10.

In [44]:
import numpy as np

#### Your code here
ary_1 = np.arange(11)
ary_1 = ary_1.astype(float)
ary_1

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

(2) Create an array containing 7 evenly spaced numbers between 0 and 23.

In [41]:
#### Your code here
ary_2 = np.linspace(0,23,7)
ary_2

array([ 0.        ,  3.83333333,  7.66666667, 11.5       , 15.33333333,
       19.16666667, 23.        ])

(3) Create a 3x3 matrix with values ranging from 0 to 8.

In [43]:
#### Your code here
ary_3 = np.arange(9)
ary_3 = ary_3.reshape([3,3])
ary_3

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

(4) Create a 5x5 matrix with row values ranging from 0 to 4.

$$\left[
\begin{array}{cc}
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 \\
0 & 1 & 2 & 3 & 4 
\end{array}
\right]$$

In [49]:
#### Your code here
ary_4 = np.zeros((5,5)) + np.arange(5)
ary_4

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

(5) A magic square is a matrix all of whose row sums, column sums and the sums of the two diagonals are the same. (One diagonal of a matrix goes from the top left to the bottom right, the other diagonal goes from top right to bottom left.)

Further more, a $n \times n$ magic matrix is constructed by $(1, 2, 3 ... n^2)$. For example, here is a $3\times 3$ magic array:
$$\left[
\begin{array}{cc}
8 & 1 & 6 \\
3 & 5 & 7 \\
4 & 9 & 2
\end{array}
\right]$$

Each number can only be used once.

Write a function to check whether a matrix is a magic matrix. You should check these three properties:

1. Is it a square matrix?
2. Is it constructed by $(1, 2, 3, ... n^2)$?
3. Are the sums of rows, columns and diags the same? (Hint: the function **np.diag** may be useful)


In [89]:
matrix2 = np.array([[8,1,6],
          [3,5,7],
          [4,9,2]])
shape = matrix2.shape
#any([i in matrix2 for i in range(1,10)])
len(matrix2)**2
sum(matrix2[0])
np.diag(matrix2)
np.fliplr(matrix2)
a = [sum(matrix2[i]) for i in range(len(matrix2))]
b = [sum(np.diag(np.fliplr(matrix2)))]
print(a)
print(b)
len(set(a + b))

[15, 15, 15]
[15]


1

In [90]:
#### Your code here  
def isMagic(matrix):
    shape = matrix.shape
    size = len(matrix2)**2
    flipmatrix = np.fliplr(matrix)
    
    #check square matrix
    if shape[0] != shape[1]:
        return False
    else:
        # check construction
        if any([i in matrix for i in range(1,1+size)]) == False:
            return False
        else:
            # check sums
            rowsums = [sum(matrix[i]) for i in range(len(matrix))]
            colsums = [sum(matrix[:,i]) for i in range(len(matrix))]
            diagsum = [sum(np.diag(matrix)),sum(np.diag(np.fliplr(matrix)))]
            allsums = rowsums + colsums + diagsum
            if len(set(allsums)) != 1:
                return False
            else:
                return True

Here are some tests:

In [91]:
test1 = np.array([[0, 1], 
                  [1, 0]])
isMagic(test1) # False

False

In [92]:
test2 = np.array([[8, 1, 6],
                  [3, 5, 7],
                  [4, 9, 2]])
isMagic(test2) # True

True

In [93]:
test3 = np.array([[2, 6, 7],
                  [4, 8, 3],
                  [9, 1, 5]])
isMagic(test3) # False

False

In [94]:
test4 = np.array([[16, 2, 3, 13],
                  [5, 11, 10, 8],
                  [9,  7, 6, 12],
                  [4, 14, 15, 1]]) 
isMagic(test4) # True

True

In [95]:
test5 = np.array([[17, 24,  1,  8, 15],
                  [23,  5,  7, 14, 16],
                  [4,   6, 13, 20, 22],
                  [10, 12, 19, 21,  3],
                  [11, 18, 25, 2,   9]]) 
isMagic(test5) # True

True

In [96]:
test6 = np.array([[35, 1, 6, 26, 19, 24],
                  [3, 32, 7, 21, 23, 25],
                  [31, 9, 2, 22, 27, 20],
                  [8, 28, 33, 17, 10,15],
                  [30, 5, 34, 12, 14,16],
                  [4, 36, 29, 13, 18,11]])
isMagic(test6) # True

True

### Problem 3


We discuss random sampling in the class, which helps when exact solution is hard to obtain. For example, we know that the area of a circle is $\pi \times r^2 \text{, where } r \text{ is the radius of the circle. }$ But we don't know how to approximate the number $\pi$.

Monte Carlo simulation can help.

<img src=https://s3.amazonaws.com/nycdsabt01/monte_carlo.png width=330/>

- Use `np.random.uniform` function to generate 2000 two dimensional samples. `uniform` indicates that the likelihood for any number from **-1 to 1** occurs is uniform. The shape of your sample should look like below (of course the actual numbers can be different)
```
array([[-0.53277773, -0.93122476],
        [ 0.16017788, -0.74177143],
        [ 0.37248292,  0.36734988],
        ..., 
        [ 0.5314644 , -0.50411338],
        [ 0.12208452,  0.6242463 ],
        [ 0.74767075, -0.56486567]])
```
Therefore all the samples fall in the $[-1, 1] \times [-1, 1] \text{ box.}$

In [107]:
import numpy as np
#### Your code here
np.random.seed(1)
sample = np.random.uniform(-1,1,(2000,2))

- The probability of points being in the circle is the ratio between the area of the circle and the area of the $[-1, 1] \times [-1, 1] \text{ box.}$ More precisely,

$$\text{Probability} \big( \text{points falling in the circle} \big) = \frac{\text{area of the circle}}{\text{area of the rectangle}} = \frac{\pi}{4},$$

From the sample you generate in the last problem, estimate the probability of falling in the circle, then approximate $\pi$.

In [115]:
#### Your code here
sums = [i[0]**2 + i[1]**2 for i in sample]
sums = np.array(sums)
estimate = 4*len(sums[sums<=1])/2000
estimate

3.146